### ISSUE TITLE
Unable to get the login for sify

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manki/msify#1]
```
What steps will reproduce the problem?
1.Extract msify-1.0.10.zip
2.edited the .sify file as per instructions
3.run ./msify 

What is the expected output? What do you see instead?
savin@savin-laptop:~$ cd msify/
savin@savin-laptop:~/msify$ ./msify.py 
Traceback (most recent call last):
  File "./msify.py", line 100, in <module>
    sys.exit(main(sys.argv))
  File "./msify.py", line 93, in main
    window = MSifyWindow()
  File "./msify.py", line 18, in __init__
    self._client = sify.SifyClient()
  File "/home/savin/msify/sify.py", line 36, in __init__
    self._InitSession()
  File "/home/savin/msify/sify.py", line 42, in _InitSession
    self._sess = minidom.parse(self.sess_file)
  File "/usr/lib/python2.5/site-packages/_xmlplus/dom/minidom.py", line
1915, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python2.5/site-packages/_xmlplus/dom/expatbuilder.py",
line 926, in parse
    result = builder.parseFile(fp)
  File "/usr/lib/python2.5/site-packages/_xmlplus/dom/expatbuilder.py",
line 211, in parseFile
    parser.Parse("", True)
xml.parsers.expat.ExpatError: no element found: line 2, column 0
savin@savin-laptop:~/msify$ 



What version of the product are you using? On what operating system?
savin@savin-laptop:~/msify$ uname -a
Linux savin-laptop 2.6.22-14-generic #1 SMP Tue Dec 18 08:02:57 UTC 2007
i686 GNU/Linux

Please provide any additional information below.

savin@savin-laptop:~/msify$ aptitude show python
Package: python
State: installed
Automatically installed: yes
Version: 2.5.1-1ubuntu2
Priority: important
Section: python
Maintainer: Ubuntu Core Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Uncompressed Size: 614k
Depends: python2.5 (>= 2.5), python-minimal (= 2.5.1-1ubuntu2)
Suggests: python-doc (>= 2.5.1-1ubuntu2), python-tk (>= 2.5.1-1ubuntu2),
          python-profiler (>= 2.5.1-1ubuntu2)
Conflicts: python2.3 (< 2.3.5-14), python2.1 (<= 2.1.2), python-xmlbase,
           python-csv, python-bz2, python-base, python-central (< 0.5.5)
Replaces: python2.3 (<= 2.3.2-6), python-xmlbase, python-base
Provides: python-email, python-xmlbase
Description: An interactive high-level object-oriented language (default
version)
 Python, the high-level, interactive object oriented language, includes an
 extensive class library with lots of goodies for network programming, system
 administration, sounds and graphics. 

 This package is a dependency package, which depends on Debian's default Python
 version (currently v2.5).

savin@savin-laptop:~/msify$ aptitude show python-beautifulsoup
Package: python-beautifulsoup
State: installed
Automatically installed: yes
Version: 3.0.4-1build1
Priority: optional
Section: universe/web
Maintainer: Ubuntu MOTU Developers <ubuntu-motu@lists.ubuntu.com>
Uncompressed Size: 160k
Depends: python (>= 2.2), python-support (>= 0.2)
Conflicts: python2.3-beautifulsoup (< 3.0.1-2), python2.4-beautifulsoup (<
           3.0.1-2)
Replaces: python2.3-beautifulsoup (< 3.0.1-2), python2.4-beautifulsoup (<
          3.0.1-2)
Provides: python2.3-beautifulsoup, python2.4-beautifulsoup,
          python2.5-beautifulsoup
Description: error-tolerant HTML parser for Python
 The BeautifulSoup class turns arbitrarily bad HTML into a tree-like nested
 tag-soup list of Tag objects and text snippets. A Tag object corresponds to an
 HTML tag.  It knows about the HTML tag's attributes, and contains a
 representation of everything contained between the original tag and its
closing
 tag (if any). It's easy to extract Tags that meet certain criteria.






```

Original issue reported on code.google.com by `savin...@gmail.com` on 27 Jan 2008 at 8:50

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I am getting the same error except for this line:
  xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

Original comment by `mustali....@gmail.com` on 1 May 2008 at 10:55

**Comment by GoogleCodeExporter** [comment]
```
Same as mustali.dalal...

can you please advise how to fix this error...thankx
```

Original comment by `thakur.g...@gmail.com` on 18 May 2008 at 12:57

**Comment by GoogleCodeExporter** [comment]
```
i use ubuntu 8
i followed all the steps as were stated....

now when i run the program( ~~$./msify.py ) then it gives following error....
can some one help...
i see others facing similar problem...

Traceback (most recent call last):
  File "./msify.py", line 100, in <module>
    sys.exit(main(sys.argv))
  File "./msify.py", line 93, in main
    window = MSifyWindow()
  File "./msify.py", line 18, in __init__
    self._client = sify.SifyClient()
  File "/home/savin/msify/sify.py", line 36, in __init__
    self._InitSession()
  File "/home/savin/msify/sify.py", line 42, in _InitSession
    self._sess = minidom.parse(self.sess_file)
  File "/usr/lib/python2.5/site-packages/_xmlplus/dom/minidom.py", line
1915, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python2.5/site-packages/_xmlplus/dom/expatbuilder.py",
line 926, in parse
    result = builder.parseFile(fp)
  File "/usr/lib/python2.5/site-packages/_xmlplus/dom/expatbuilder.py",
line 211, in parseFile
    parser.Parse("", True)
xml.parsers.expat.ExpatError: no element found: line 2, column 0
```

Original comment by `kumar.pr...@gmail.com` on 11 Jun 2008 at 1:15

**Comment by GoogleCodeExporter** [comment]
```
looks like this project is not active. Try supersify, it works like a charm.
```

Original comment by `mustali....@gmail.com` on 11 Jun 2008 at 1:21

**Comment by GoogleCodeExporter** [comment]
```
Sify servers probably don't recognise the Authentication mechanism specified 
here. 
So .sess_file doesn't get written. Hence parseFile on that fails.

Need to update the scripts as per http://broadbandforum.in/sify-broadband/15416-
steppenwolf-takes-sify-broadband-encryption-algorithm/
```

Original comment by `pratika...@gmail.com` on 1 Oct 2008 at 4:27

**Comment by GoogleCodeExporter** [comment]
```
hi everybody,
After following all the instructions regarding installation of msify i get the 
following error:

Traceback (most recent call last):  File "./msify.py", line 9, in <module> from 
PyQt4 import QtCore
ImportError: No module named PyQt4 sachin@sachin:~/msify$ 

Can anybody help me on this. I cannot connect to the internet. 

Thanks.
```

Original comment by `sachin.s...@gmail.com` on 16 Jul 2011 at 12:27
